//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.14 at 12:03:17 PM MESZ 
//

package ch.ethz.vppserver.schema.ippclient;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the ch.ethz.vppserver.schema.ippclient package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: ch.ethz.vppserver.schema.ippclient
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link AttributeValue }
   * 
   */
  public AttributeValue createAttributeValue() {
    return new AttributeValue();
  }

  /**
   * Create an instance of {@link Attribute }
   * 
   */
  public Attribute createAttribute() {
    return new Attribute();
  }

  /**
   * Create an instance of {@link Keyword }
   * 
   */
  public Keyword createKeyword() {
    return new Keyword();
  }

  /**
   * Create an instance of {@link AttributeGroup }
   * 
   */
  public AttributeGroup createAttributeGroup() {
    return new AttributeGroup();
  }

  /**
   * Create an instance of {@link SetOfEnum }
   * 
   */
  public SetOfEnum createSetOfEnum() {
    return new SetOfEnum();
  }

  /**
   * Create an instance of {@link SetOfKeyword }
   * 
   */
  public SetOfKeyword createSetOfKeyword() {
    return new SetOfKeyword();
  }

  /**
   * Create an instance of {@link Enum }
   * 
   */
  public Enum createEnum() {
    return new Enum();
  }

  /**
   * Create an instance of {@link AttributeList }
   * 
   */
  public AttributeList createAttributeList() {
    return new AttributeList();
  }

  /**
   * Create an instance of {@link TagList }
   * 
   */
  public TagList createTagList() {
    return new TagList();
  }

  /**
   * Create an instance of {@link Tag }
   * 
   */
  public Tag createTag() {
    return new Tag();
  }

}
